server:
  port: 8090

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/studentForum?serverTimezone=UTC
    username: root
    password: 0000****
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        ddl-auto: update
        use_sql_comments: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  cors:
    allowedOrigins: http://localhost:3000
